name: Deploy to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd front
          npm install
          npm run build
          echo ${{ secrets.EC2_PRIVATE_KEY }} | tr -d '\r' > $GITHUB_WORKSPACE/front/ec2_key.pem
          chmod 400 $GITHUB_WORKSPACE/front/ec2_key.pem
          scp -i $GITHUB_WORKSPACE/front/ec2_key.pem -o "StrictHostKeyChecking=no" -r ./build ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/www
