name: Deploy to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test workspace variable
        run: |
          echo $GITHUB_WORKSPACE

      - name: Install dependencies
        run: |
          cd front
          npm install
          npm run build
          # echo "build fin"
          # echo ${{ secrets.EC2_PRIVATE_KEY }} > $GITHUB_WORKSPACE/front/ec2_key.pem
          # echo "ec2key"
          # chmod 400 $GITHUB_WORKSPACE/front/ec2_key.pem
          # scp -i $GITHUB_WORKSPACE/front/ec2_key.pem -o "StrictHostKeyChecking=no" -r $GITHUB_WORKSPACE/front/build ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/www

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "$GITHUB_WORKSPACE/front/build"
          target: "/home/${{ secrets.EC2_USERNAME }}/www"
