name: Deploy to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test workspace variable
        run: |
          echo $GITHUB_WORKSPACE

      - name: Install dependencies
        run: |
          cd front
          npm install
          npm run build
          ls -al build

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "$GITHUB_WORKSPACE/front/build"
          target: "/home/${{ secrets.EC2_USERNAME }}/www"
