name: Deploy to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd front
          ls
          npm install
          npm run build
          echo ${{ secrets.EC2_PRIVATE_KEY }} > ec2_key.pem
          scp -i ec2_key.pem -r ./build ${{ secrets.EC2_HOST }}@${{ secrets.EC2_USERNAME }}

      # - name: Copy files to EC2 instance
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_PRIVATE_KEY }}
      #     source: "front/build/"
      #     target: "/home/ubuntu/www"
