name: Deploy to Back EC2 instance

on:
  push:
    branches:
      - main
    paths:
      - "back/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: back
        run: |
          npm install

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_BACK_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "back"
          target: "/home/${{ secrets.EC2_USERNAME }}/www"

      - name: Node Restart
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_BACK_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: echo "hello" > test.txt
