name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Frontend 빌드 & 배포
      - name: Frontend deployment
        if: ${{ github.event.head_commit.modified_files | contains('front/') }}
        env:
          TARGET_DIR: "/home/${{ secrets.EC2_USERNAME }}/www/front"
        run: |
          cd front
          npm install
          npm run build
          echo "build fin"
          scp -r -i ${{ secrets.EC2_PRIVATE_KEY }} -o "StrictHostKeyChecking=no" ./build ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:$TARGET_DIR
