name: Deploy to EC2 instance

on:
  push:
    branches:
      - main
    paths:
      - "front/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: front
        run: |
          npm install
          npm run build

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "front/build"
          target: "/home/${{ secrets.EC2_USERNAME }}/www"
